language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: KcPzqqv8JjKPtzA76MOXjwAKX3zfeRRekmPZLmIo0YGii8iV+dv4pz4RC1z/SvqwteyLJ5Am2EIAaLEFi8Lt5yefc26C7GSF1YBQB+q0h/RZDUyNaifJvo12Bo2POgVNNetH9IBQx7Z65Ga7/vvZNthNwLl+PtlUxe3viaZltanY2ZdQJS9+1Lc27MCCqR9/HhL1K5HSYqbkmdnL05yalBmtUMmH4LLEvC9pCU//leMGwoOM10xXkpJrxu7PELWI+Olhcc//lgfujf0NO3DAZAStVI6f52AJwpQ5fRHBWqR18d7bMeLirFR2X/xzfzTLCB59+B6JK/Ym1EfLtpcvTdjLK3zOabQ4+mirMim2VW8sDATp0NtnkSfITfQQOMSGpVyiEvUI3svCl0fb3W9FcnNG8ZO4W+Nb1CGquydKTukTjZKVtPfJWhUm8lSGH1fwP+OLPliAJJU0yiesscpxyrM3rL52rzYsulhLj/1JT5HYzqCRjiq7U20Gcw2SZLRQ20Mk3SflPeJLWXbRYn2ccoevW0LEtsADxDlks3zFrbgK6dm4KOOP0QfQOpqSY64fcUzyKtYagYSMdwZz4tAhVyGHkwbS2J1UYi1E+Z4oigBDliOskGy/7Rjyxkb9Q2qMTfEfuont1cOAVogUIOiRo/FlGMnOWeuXvzx/bc2PxXY=
  - secure: rkSlwZGAEmeqenoztCeCSwcmK429IIpHuHyqJdwheT4phPKZzxvjZcjvX+BxercwzH3T+zoDdCmqdZCmMNwN0s63xEX4SLiKIJIVAqo3sSbhQ7cfdZra4zRX+rC1OCstXtG4x8Fr+n0Mg5Swwu+neVLlggogyuhCxmRvHf9ZwueG7Z6eNnl075BwGW8VlElTiu1MPj94pOL1NJ6CdNrInSLsISRXYs/HCfq7+a+nVK1wMp4no1anMoJR3JkApWr72Chtqv6Vwz4RfxXGt/lTuf1+nsFeckhr4lAu+fwg1hrzscL35EwwWWynRya/0tImU2RtCv3UalJhC374aulUH6t91/cyjMiDGFkzH0qGPHb0fi9VolQBlgFMFPXeLCMOHvqkae9WmUS3R1gjicFJXaCiKTMlRM87kxO+Zpk6uHd6Ne7Vas+xxSshlSaE8I+tFxtqI0xNmN8iJFFwMieSz82r13bN1pq25yEQNmq6ERvwSakpwovp9p/AY/Of+bSqAhXoOUq83tsHZzxywyTM2d+f81v0UVZzephXgXLTpN6J1AHjKhGo1Yo/lIZctfCgAMXg9wJQaWF9m+YiMlcQflpzxAJiX28W4AIuIpAgOoU1GyiLgr8aIGBTmXQBS9VdRIHP8w1T7SdyPYKlyVKJJ/mUi3/KkaBFmwYc6wmZpHE=
  - secure: dMtEQfCzRpSHknJg1Q7/G/T0/hpJpknG8gey4/Ah472Bb5CekcIZXh1U/wk6OEYT1bP9k7HU6Yggyr8WMd4dzjfwOWK8oEJAnUSPSmPieGS8eJ4OPbYbfzBe2dEXoT3Pv3sK3SQbPz34bLtKsDo7J1XrSxEVTdzpXlxc8+bUStAvoJBk7f9+YVX7a2jgyx5H4LY6fNreM1MaflnJkMXc8d994uTWJgeR1Quj9ddK1rai0TiYUOQwEgUZuejE4daLIwNqXXVn/7T6i+16xB6CuP9TaryXCodVGeSdUdujMO/KpXMDj1NZahm3R1ZbBQxACpHbGwEG64wYrrujHGA37Qk+K8Cy7XjsEJExwpYuxi4nAEol+K1IqY2x3VgD0uJ6cy2LVcYhW0mOVdbSMc4Jz/M4gV29JHMNQPUZuxYzb3IuuHe2H1mfW8p9hgMTEpx745Dipsz0k4nyXisK76qs6IRXrVIcVeJxk144GL34B1jv7UoSF4qlvPCjjBPVxDNPF6gL16+MeI62MEzi70dZ5Wiq/B8+sbfXTW2U2Pz+5u8DH7AudZAYGS/B/NXbiiBrrd4GeYJBKbFgcU5zv0hpwrFRza7e6hS10Q9J1lkOzdCueWDiwDkotJ/VGtGfaZTnhz/BuMNjk1vIh8HLvc7jnHlHlfM1vQ2L4uRBZIyEBOU=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package=cmake-forward-cache
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/cmake-forward-cache
    branch: master
    condition: "${DEPLOY} = 1"
