language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: AZwf7udQQDvlBl/Z+x66xZPNDQb/1orJDCqnb0KxRpaYZ+TKyw8ZwBGnoBs05Yab86fDnh9cLgjas3Xn4tJqkzI3jeAerOLUHFnK2oD8YN3tf11Vu2vRweQus69p3ydK8EVm3zWDONvjG59tRfjoZrwqtdaI244GsqleuWx4a5Uopil9tF/LkSq1DUAPO+s0FiNYSCHOKlHHMtA+kTUCsMSWwJiWyzj4/gVzBHKJdim8QxiBWtviZaFbOVWA8KsFO46MSjxfiKEOKVIIrMKDEj9I5k9tI1AU3U7xYgcq3cbDPZkK2OjzZDcaVp3LWr5/iiWidzhecX2lDQHYMtzsVA1pzzQvsFNAnXGJPztZK8CDbLldBQAxWMv8SBF0Fj0IuzarowVca9VrtmkMtxV7/veXqNQjW6m4Z+0nq4hScfaQ1cOF/hYmQmQmnENVm91KNbycklaZMXnwQoeB00ZDBBhK3kLfkVOpkxrdFWfimYGxGjrA9qz85P5kVAWKW21vChLGsQHKTiscn6Z71UHVpOB0CkbXRKplQS1ONcpISXvfjmxgZXMcRkXgcFDZ3g+7YEXaifVvrV8egJdJUs1qytpMd8Y5FjCLYcSqUV7fooDS+LLHjPBvjMly7zfAVPtjPouDWmTxkkR1zQXYB8rZsIfUR1Bu2TyFBnLrvJ4nOpI=
  - secure: eGmyraKvJ+knsu26rqm4rDCON7B/bfD6V6UEQH/TMw7fypMkngoH4zvIWvyFrdjtzJzMD25gUhpnaY9xQIXxca814A2q1uAwlB7N1fLIjUIr4AY4Te5xrDuZOI/pfzD+Zkikph5GiEhIS/IoqTcK8tRamzNNhCUI8KFPIPuoV18SDtbGdDCeLCIjDM+9PxRKLaFUub3cgYEa2v2kl5sStassLOp0J+8v64VO1cYD/LFvq+4ln2J2Czboga5SffjR/sE/Z8yYCFmKPCsBXn3NMJ0OOnKYMpYFX9JQT9floiq+4IgaQkXdeWFpT5bIp80e8kv1yA+kTPYxf4r/Bb/5P/78GY97HazDKlyWgJ9TvIzeuG1l4zuT22jh0ZSJNACEF5BvlfgF7Mk6wAOkgpxqPO1q7IsXFB2RpG9ixloWWa9mmxTTk4Fqd8KEUCVpwyu0XVicqHzeafkwol4sGLwki+snkHRQts07/iP8OZDnI14OjXhRQ+onDukVNLAM5GWs6W9Oh6vR4n6kjvIo0z6042FaisPrRBOcz8qugD+YyNfOXDFrWkH0UJgHpDE22UgO1TLzT2O3l+j3KiQIJ3jaSA7TQgDSR8DnhTNLBZNHyugMQh+d28LqfAW7WUCAB0811tczcKuuzSpvSAhggQG/fOfuV/NsY99Fk58yeLXT08U=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/script/before_deploy.py deploy/conan/deploy.py --package=cmake-forward-cache --user=$CONAN_USER --password=$CONAN_PASSWORD
deploy:
  provider: script
  skip_cleanup: true
  script: ./travis-deploy
  on:
    repo: polysquare/cmake-forward-cache
    branch: master
    condition: ${DEPLOY} = 1
